#!/bin/bash

now=$(date)
ip=$(hostname -I)

mkdir ~/research 2> /dev/null

echo "System info as of $now:" > ~/research/sys_info.txt
echo -e "Machine Type Info" >> ~/research/sys_info.txt
echo $MACHTYPE >> ~/research/sys_info.txt
echo -e "Uname info: $(uname -a) \n" >> ~/research/sys_info.txt
echo -e "IP info: $(ip addr | grep inet | tail -1) \n" >> ~/research/sys_info.txt
echo  "Hostname: $(hostname -s)" >> ~/research/sys_info.txt
echo "Memory Info:" >> ~/research/sys_info.txt
free >> ~/research/sys_info.txt
echo -e "\nCPU Info:" >> ~/research/sys_info.txt
lscpu | grep CPU >> ~/research/sys_info.txt
echo -e " " >> ~/research/sys_info.txt
sudo find /home -type f -perm 777 >> ~/research/sys_info.txt
echo -e " " >> ~/research/sys_info.txt
echo -e "\nTop 10 Processes \n" >> ~/research/sys_info.txt
ps aux --sort -%mem | awk {'print $1, $2, $3, $4, $11'} | head -11 >> ~/research/sys_info.txt
